package book.view;

import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.HashMap;
import java.util.Map;
import javax.naming.ldap.HasControls;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;

public class BookManagementForm extends javax.swing.JFrame implements IBookManagementForm{
     
    
    public BookManagementForm() {
        initComponents();
        tbShowListBook.setFillsViewportHeight(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        tabManageBook = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        tfDataSearch = new javax.swing.JTextField();
        btnSearchBook = new javax.swing.JButton();
        scrollPaneContentBooks = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbShowListBook = new javax.swing.JTable();
        cbBoxTypeOfSearchBook = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        panelShowBookInfo = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jscrollpane = new javax.swing.JScrollPane();
        tbShowBookCopyInfo = new javax.swing.JTable();
        tfShowBookNumber = new javax.swing.JTextField();
        tfShowBookName = new javax.swing.JTextField();
        tfShowBookAuthor = new javax.swing.JTextField();
        tfShowBookIBNS = new javax.swing.JTextField();
        tfShowBookPublisher = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfBookTitle = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSaveNewBook = new javax.swing.JButton();
        tfPublisher = new javax.swing.JTextField();
        tfAuthor = new javax.swing.JTextField();
        tfISBN = new javax.swing.JTextField();
        btnCancelSaveNewBook = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        cbCategoryBook = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        tfBookNumber = new javax.swing.JTextField();
        lbBookNumber = new javax.swing.JLabel();
        checkboxSelectTypeEnter = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tfBookNumberOfNewBookCopy = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfNumOfCopyBook = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfBookCopyPrince = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbBoxTypeOfCopy = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        btnSaveNewCopyBook = new javax.swing.JButton();
        btnRefreshCopyBook = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnShowBookNumber = new javax.swing.JButton();
        tfEditBookNumber = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        tfEditBookName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tfEditBookAuthor = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tfEditBookPublisher = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tfEditBookIBNS = new javax.swing.JTextField();
        btnChangeBookInfo = new javax.swing.JButton();
        btnCancelEditBookInfo = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tfBookCopyNumberEdit = new javax.swing.JTextField();
        btnShowBookCopyInfo = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        tfPrinceOfBookCopyEdit = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        cbEditTypeOfCopyEdit = new javax.swing.JComboBox<>();
        btnChangeBookCopyInfo = new javax.swing.JButton();
        btnCancelEditBookCOpy = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        tabManageBook.setBackground(new java.awt.Color(255, 255, 51));

        btnSearchBook.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnSearchBook.setForeground(new java.awt.Color(0, 51, 255));
        btnSearchBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_search.png"))); // NOI18N
        btnSearchBook.setText("Tìm kiếm");
        btnSearchBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBookActionPerformed(evt);
            }
        });

        tbShowListBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbShowListBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbShowListBookMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbShowListBookMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbShowListBook);

        scrollPaneContentBooks.setViewportView(jScrollPane1);

        cbBoxTypeOfSearchBook.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbBoxTypeOfSearchBook.setForeground(new java.awt.Color(0, 51, 255));
        cbBoxTypeOfSearchBook.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã sách", "Tên", "Tác giả", "Nhà xuất bản" }));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 255));
        jLabel7.setText("Tìm kiếm theo");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 204));
        jLabel22.setText("Tìm kiếm sách");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfDataSearch)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbBoxTypeOfSearchBook, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchBook)
                .addContainerGap())
            .addComponent(scrollPaneContentBooks, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel22)
                .addGap(54, 54, 54)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBoxTypeOfSearchBook, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDataSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchBook))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPaneContentBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel26.setForeground(new java.awt.Color(0, 102, 255));
        jLabel26.setText("Mã sách:");

        jLabel28.setForeground(new java.awt.Color(0, 102, 255));
        jLabel28.setText("Tên sách:");

        jLabel30.setForeground(new java.awt.Color(0, 102, 255));
        jLabel30.setText("Tác giả:");

        jLabel32.setForeground(new java.awt.Color(0, 102, 255));
        jLabel32.setText("NXB:");

        jLabel34.setForeground(new java.awt.Color(0, 102, 255));
        jLabel34.setText("IBNS:");

        tbShowBookCopyInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbShowBookCopyInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbShowBookCopyInfoMouseReleased(evt);
            }
        });
        jscrollpane.setViewportView(tbShowBookCopyInfo);

        tfShowBookNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfShowBookNumberKeyPressed(evt);
            }
        });

        tfShowBookName.setEditable(false);

        tfShowBookAuthor.setEditable(false);

        tfShowBookIBNS.setEditable(false);

        tfShowBookPublisher.setEditable(false);

        javax.swing.GroupLayout panelShowBookInfoLayout = new javax.swing.GroupLayout(panelShowBookInfo);
        panelShowBookInfo.setLayout(panelShowBookInfoLayout);
        panelShowBookInfoLayout.setHorizontalGroup(
            panelShowBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShowBookInfoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelShowBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelShowBookInfoLayout.createSequentialGroup()
                        .addGroup(panelShowBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel32)
                            .addComponent(jLabel34))
                        .addGap(9, 9, 9))
                    .addGroup(panelShowBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel26)
                        .addComponent(jLabel28)))
                .addGap(52, 52, 52)
                .addGroup(panelShowBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfShowBookIBNS, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfShowBookName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfShowBookNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfShowBookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfShowBookPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
            .addComponent(jscrollpane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        panelShowBookInfoLayout.setVerticalGroup(
            panelShowBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShowBookInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelShowBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(tfShowBookNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelShowBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(tfShowBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelShowBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(tfShowBookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelShowBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(tfShowBookPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelShowBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(tfShowBookIBNS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jscrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 204));
        jLabel13.setText("Thông tin sách");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(175, 175, 175))
                    .addComponent(panelShowBookInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelShowBookInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        tabManageBook.addTab("Tìm kiếm sách", jPanel2);

        jLabel3.setText("Tên sách:");

        tfBookTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBookTitleActionPerformed(evt);
            }
        });

        jLabel4.setText("NXB:");

        jLabel5.setText("ISBN:");

        jLabel6.setText("Tác giả:");

        btnSaveNewBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_save.png"))); // NOI18N
        btnSaveNewBook.setText("Lưu");
        btnSaveNewBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveNewBookActionPerformed(evt);
            }
        });

        btnCancelSaveNewBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_refresh.png"))); // NOI18N
        btnCancelSaveNewBook.setText("Làm mới");

        jLabel25.setText("Thể loại:");

        cbCategoryBook.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Nhập mã sách"));

        tfBookNumber.setEnabled(false);

        lbBookNumber.setText("Số sách:");
        lbBookNumber.setEnabled(false);

        checkboxSelectTypeEnter.setText("Thủ công");
        checkboxSelectTypeEnter.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkboxSelectTypeEnterStateChanged(evt);
            }
        });
        checkboxSelectTypeEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxSelectTypeEnterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(checkboxSelectTypeEnter)
                        .addContainerGap(291, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(lbBookNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfBookNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(checkboxSelectTypeEnter)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBookNumber)
                    .addComponent(tfBookNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbCategoryBook, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5))
                                    .addGap(44, 44, 44)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfISBN, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                                        .addComponent(tfBookTitle)
                                        .addComponent(tfPublisher)
                                        .addComponent(tfAuthor))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(btnSaveNewBook, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(btnCancelSaveNewBook)))
                .addContainerGap(391, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCategoryBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(tfPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveNewBook, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelSaveNewBook, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        tabManageBook.addTab("Thêm sách mới", jPanel1);

        jLabel8.setText("Số sách:");

        jLabel9.setText("Số lượng bản sao");

        jLabel10.setText("Giá sách:");

        tfBookCopyPrince.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBookCopyPrinceActionPerformed(evt);
            }
        });

        jLabel11.setText("Loại:");

        cbBoxTypeOfCopy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cho mượn", "Tham khảo" }));

        jLabel12.setText("(VNĐ)");

        btnSaveNewCopyBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_save.png"))); // NOI18N
        btnSaveNewCopyBook.setText("Thêm");
        btnSaveNewCopyBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveNewCopyBookActionPerformed(evt);
            }
        });

        btnRefreshCopyBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_refresh.png"))); // NOI18N
        btnRefreshCopyBook.setText("Làm mới");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfBookNumberOfNewBookCopy)
                            .addComponent(tfNumOfCopyBook)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbBoxTypeOfCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfBookCopyPrince, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(btnSaveNewCopyBook, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(btnRefreshCopyBook)))
                .addContainerGap(440, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfBookNumberOfNewBookCopy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfNumOfCopyBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfBookCopyPrince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbBoxTypeOfCopy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveNewCopyBook)
                    .addComponent(btnRefreshCopyBook))
                .addContainerGap(246, Short.MAX_VALUE))
        );

        tabManageBook.addTab("Thêm sách bản sao", jPanel4);

        btnShowBookNumber.setText("Hiển thị thông tin");
        btnShowBookNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowBookNumberActionPerformed(evt);
            }
        });

        jLabel16.setText("Số sách:");

        jLabel15.setText("SỬA THÔNG TIN SÁCH");

        jLabel14.setText("Tên sách:");

        jLabel17.setText("Tác giả:");

        jLabel18.setText("NXB:");

        jLabel20.setText("IBNS:");

        btnChangeBookInfo.setText("Cập nhật thông tin");
        btnChangeBookInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeBookInfoActionPerformed(evt);
            }
        });

        btnCancelEditBookInfo.setText("Hủy bỏ");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel18))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfEditBookPublisher)
                                    .addComponent(tfEditBookIBNS, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(38, 38, 38)
                                .addComponent(tfEditBookName, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(47, 47, 47)
                                .addComponent(tfEditBookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnChangeBookInfo)
                        .addGap(35, 35, 35)
                        .addComponent(btnCancelEditBookInfo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tfEditBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tfEditBookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tfEditBookPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tfEditBookIBNS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChangeBookInfo)
                    .addComponent(btnCancelEditBookInfo))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfEditBookNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnShowBookNumber)
                        .addGap(0, 47, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEditBookNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShowBookNumber)
                    .addComponent(jLabel16))
                .addGap(54, 54, 54)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel19.setText("SỬA THÔNG TIN BẢN SAO");

        jLabel21.setText("Mã sách bản sao:");

        btnShowBookCopyInfo.setText("Hiên thị");
        btnShowBookCopyInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowBookCopyInfoActionPerformed(evt);
            }
        });

        jLabel23.setText("Giá sách:");

        jLabel24.setText("Loại:");

        cbEditTypeOfCopyEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cho mượn", "Tham khảo" }));

        btnChangeBookCopyInfo.setText("Cập nhật");
        btnChangeBookCopyInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeBookCopyInfoActionPerformed(evt);
            }
        });

        btnCancelEditBookCOpy.setText("Hủy");

        jLabel2.setText("VNĐ");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(112, 112, 112))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21)
                            .addComponent(btnChangeBookCopyInfo))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfBookCopyNumberEdit)
                                    .addComponent(tfPrinceOfBookCopyEdit)
                                    .addComponent(cbEditTypeOfCopyEdit, 0, 133, Short.MAX_VALUE))
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(btnShowBookCopyInfo))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2))))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(btnCancelEditBookCOpy))))
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tfBookCopyNumberEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShowBookCopyInfo))
                .addGap(24, 24, 24)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(tfPrinceOfBookCopyEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(cbEditTypeOfCopyEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChangeBookCopyInfo)
                    .addComponent(btnCancelEditBookCOpy))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tabManageBook.addTab("Sửa thông tin sách", jPanel3);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("QUẢN LÝ SÁCH");

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back_icon.png"))); // NOI18N
        btnBack.setText("Quay lai");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(324, 324, 324)
                .addComponent(btnBack))
            .addComponent(tabManageBook)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabManageBook))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfBookTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBookTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBookTitleActionPerformed

    private void tfBookCopyPrinceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBookCopyPrinceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBookCopyPrinceActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void checkboxSelectTypeEnterStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkboxSelectTypeEnterStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxSelectTypeEnterStateChanged
   
    
    private void checkboxSelectTypeEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxSelectTypeEnterActionPerformed
        if(checkboxSelectTypeEnter.isSelected()) {
            lbBookNumber.setEnabled(true);
            tfBookNumber.setEnabled(true);
        }
        else{
            lbBookNumber.setEnabled(false);
            tfBookNumber.setEnabled(false);
            
        }
    }//GEN-LAST:event_checkboxSelectTypeEnterActionPerformed
    
    private void btnSaveNewBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveNewBookActionPerformed
        
    }//GEN-LAST:event_btnSaveNewBookActionPerformed

    private void btnSearchBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBookActionPerformed
       
    }//GEN-LAST:event_btnSearchBookActionPerformed

    private void tbShowListBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbShowListBookMouseClicked
        
        
    }//GEN-LAST:event_tbShowListBookMouseClicked

    private void tfShowBookNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfShowBookNumberKeyPressed
      
    }//GEN-LAST:event_tfShowBookNumberKeyPressed

    private void btnSaveNewCopyBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveNewCopyBookActionPerformed
       
    }//GEN-LAST:event_btnSaveNewCopyBookActionPerformed

    private void tbShowListBookMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbShowListBookMouseReleased

    }//GEN-LAST:event_tbShowListBookMouseReleased

    private void tbShowBookCopyInfoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbShowBookCopyInfoMouseReleased
       
    }//GEN-LAST:event_tbShowBookCopyInfoMouseReleased

    private void btnChangeBookInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeBookInfoActionPerformed
       
    }//GEN-LAST:event_btnChangeBookInfoActionPerformed

    private void btnShowBookNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowBookNumberActionPerformed
       
    }//GEN-LAST:event_btnShowBookNumberActionPerformed

    private void btnShowBookCopyInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowBookCopyInfoActionPerformed
       
    }//GEN-LAST:event_btnShowBookCopyInfoActionPerformed

    private void btnChangeBookCopyInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeBookCopyInfoActionPerformed
        
    }//GEN-LAST:event_btnChangeBookCopyInfoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancelEditBookCOpy;
    private javax.swing.JButton btnCancelEditBookInfo;
    private javax.swing.JButton btnCancelSaveNewBook;
    private javax.swing.JButton btnChangeBookCopyInfo;
    private javax.swing.JButton btnChangeBookInfo;
    private javax.swing.JButton btnRefreshCopyBook;
    private javax.swing.JButton btnSaveNewBook;
    private javax.swing.JButton btnSaveNewCopyBook;
    private javax.swing.JButton btnSearchBook;
    private javax.swing.JButton btnShowBookCopyInfo;
    private javax.swing.JButton btnShowBookNumber;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JComboBox<String> cbBoxTypeOfCopy;
    private javax.swing.JComboBox<String> cbBoxTypeOfSearchBook;
    private javax.swing.JComboBox<String> cbCategoryBook;
    private javax.swing.JComboBox<String> cbEditTypeOfCopyEdit;
    private javax.swing.JCheckBox checkboxSelectTypeEnter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jscrollpane;
    private javax.swing.JLabel lbBookNumber;
    private javax.swing.JPanel panelShowBookInfo;
    private javax.swing.JScrollPane scrollPaneContentBooks;
    private javax.swing.JTabbedPane tabManageBook;
    private javax.swing.JTable tbShowBookCopyInfo;
    private javax.swing.JTable tbShowListBook;
    private javax.swing.JTextField tfAuthor;
    private javax.swing.JTextField tfBookCopyNumberEdit;
    private javax.swing.JTextField tfBookCopyPrince;
    private javax.swing.JTextField tfBookNumber;
    private javax.swing.JTextField tfBookNumberOfNewBookCopy;
    private javax.swing.JTextField tfBookTitle;
    private javax.swing.JTextField tfDataSearch;
    private javax.swing.JTextField tfEditBookAuthor;
    private javax.swing.JTextField tfEditBookIBNS;
    private javax.swing.JTextField tfEditBookName;
    private javax.swing.JTextField tfEditBookNumber;
    private javax.swing.JTextField tfEditBookPublisher;
    private javax.swing.JTextField tfISBN;
    private javax.swing.JTextField tfNumOfCopyBook;
    private javax.swing.JTextField tfPrinceOfBookCopyEdit;
    private javax.swing.JTextField tfPublisher;
    private javax.swing.JTextField tfShowBookAuthor;
    private javax.swing.JTextField tfShowBookIBNS;
    private javax.swing.JTextField tfShowBookName;
    private javax.swing.JTextField tfShowBookNumber;
    private javax.swing.JTextField tfShowBookPublisher;
    // End of variables declaration//GEN-END:variables

    @Override
    public void openBookManageForm() {
        this.setVisible(true);
    }

    @Override
    public void hideBookManagementForm() {
        this.setVisible(false);
    }

    @Override
    public void setButtonBackAction(ActionListener listener) {
        btnBack.addActionListener(listener);
    }

    @Override
    public void setButtonSaveNewBookAction(ActionListener listener) {
        btnSaveNewBook.addActionListener(listener);
    }

    @Override
    public void setButtonCansaveNewBookAction(ActionListener listener) {
        btnCancelSaveNewBook.addActionListener(listener);
    }

    @Override
    public void setButtonSearchBookAction(ActionListener listener) {
        btnSearchBook.addActionListener(listener);
    }

    @Override
    public void setTextFieldSearchBookKeyAction(KeyListener listener) {
        tfDataSearch.addKeyListener(listener);
    }

    @Override
    public void setCheckBoxTypeEnterBookActionListener(ActionListener listener) {
        checkboxSelectTypeEnter.addActionListener(listener);
    }

    @Override
    public void enableEnterBookNumber() {
        lbBookNumber.setEnabled(true);
        tfBookNumber.setEnabled(true);
    }
    
    @Override
    public void disableEnterBookNumber() {
        lbBookNumber.setEnabled(false);
        tfBookNumber.setEnabled(false);
    }
    
    @Override
    public boolean getCheckBoxSelectTypeEnter(){
        return checkboxSelectTypeEnter.isSelected();
    }

    @Override
    public String getTextFieldBookNumberOnSaveBook() {
        return tfBookNumber.getText();
    }

    @Override
    public String getTextFieldBookTitleOnSaveBook() {
        return tfBookTitle.getText();
    }

    @Override
    public String getTextFieldBookAuthorOnSaveBook() {
        return tfAuthor.getText();
    }

    @Override
    public String getTextFieldBookPublisherOnSaveBook() {
        return tfPublisher.getText();
    }

    @Override
    public String getTextFieldBookIBNSOnSaveBook() {
        return tfISBN.getText();
    }
    
    @Override
    public void showListCategoryBook(MyComboboxModel data){
        cbCategoryBook.setModel(data);
        cbCategoryBook.setSelectedIndex(0);
    }

    @Override
    public int getComboBoxCategoryBookOnSaveBook() {
        return cbCategoryBook.getSelectedIndex();
    }

    @Override
    public void noticeError(String title, String message) {
        JOptionPane.showMessageDialog(this,message, title, JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public void noticeSuccessfully(String title, String message) {
        JOptionPane.showMessageDialog(this,message, title, JOptionPane.INFORMATION_MESSAGE);
    }

    @Override
    public void setButonSaveNewBookCopyActionListener(ActionListener listener) {
        btnSaveNewCopyBook.addActionListener(listener);
    }

    @Override
    public void setButtonRefreshSaveBookCopyActionListener(ActionListener listener) {
        btnRefreshCopyBook.addActionListener(listener);
    }

    @Override
    public String getTextFieldBookNumberOfNewBookCopy() {
        return tfBookNumberOfNewBookCopy.getText();
    }

    @Override
    public String getTextFieldNumOfCopyBook() {
        return tfNumOfCopyBook.getText();
    }

    @Override
    public String getTextFieldBookCopyPrince() {
        return tfBookCopyPrince.getText();
    }

    @Override
    public int getComboBoxBoxTypeOfCopy() {
        return cbBoxTypeOfCopy.getSelectedIndex();
    }

    @Override
    public int getComboBoxTypeOfSearchBook() {
        return cbBoxTypeOfSearchBook.getSelectedIndex();
    }

    @Override
    public String getTextFieldDataSearch() {
        return tfDataSearch.getText();
    }

    @Override
    public void displayBookResult(BookTableModel bookTableModel) {
        tbShowListBook.setModel(bookTableModel);
    }

    @Override
    public void setTextFieldDataSearchKeyAction(KeyListener listener) {
        tfDataSearch.addKeyListener(listener);
    }

    @Override
    public void doClickButtonSearchBook() {
        btnSearchBook.doClick();
    }

    @Override
    public void setTableShowBookResultMouseAction(MouseListener listener) {
        tbShowListBook.addMouseListener(listener);
    }

    @Override
    public void setTextFieldShowBookNumber(String bookNumber) {
        tfShowBookNumber.setText(bookNumber);
    }

    @Override
    public void setTextFieldShowBookName(String bookNumber) {
        tfShowBookName.setText(bookNumber);
    }

    @Override
    public void setTextFieldShowBookAuthor(String author) {
        tfShowBookAuthor.setText(author);
    }

    @Override
    public void setTextFieldShowBookPublisher(String publisher) {
        tfShowBookPublisher.setText(publisher);
    }

    @Override
    public void setTextFieldShowIBNS(String ibns) {
        tfShowBookIBNS.setText(ibns);
    }

    @Override
    public void showTableListBookCopyInfo(BookCopyTableModel bookCopyTableModel) {
        tbShowBookCopyInfo.setModel(bookCopyTableModel);
    }

    @Override
    public int getTableListBookResultRowSelected(MouseEvent e) {
        return tbShowListBook.rowAtPoint(e.getPoint());
    }

    @Override
    public void setTableShowBookCopyMouseAction(MouseListener listener) {
        tbShowBookCopyInfo.addMouseListener(listener);
    }

    @Override
    public int getTableListBookCopyResultRowSelected(MouseEvent e) {
        return tbShowBookCopyInfo.rowAtPoint(e.getPoint());
    }

    @Override
    public void setTableBookCopySelectRow(int row) {
        tbShowBookCopyInfo.setRowSelectionInterval(row,row);
    }

    @Override
    public void showBookInfoToEdit(String bookNumber, String bookName, String bookAuthor, String bookPublisher, String ibns) {
        tfEditBookNumber.setText(bookNumber);
        tfEditBookName.setText(bookName);
        tfEditBookAuthor.setText(bookAuthor);
        tfEditBookPublisher.setText(bookPublisher);
        tfEditBookIBNS.setText(ibns);
    }

    @Override
    public void setTableShowListBookSelected(int row) {
        tbShowListBook.setRowSelectionInterval(row,row);
    }

    @Override
    public void showBookCopyInfoToEdit(int currentPosition) {

    }
}
