package book.view;


public class PanelShowBookInfo extends javax.swing.JPanel {

    /**
     * Creates new form PanelShowBookInfo
     */
    public PanelShowBookInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelShowBookInfo = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jscrollpane = new javax.swing.JScrollPane();
        tbShowBookCopyInfo = new javax.swing.JTable();
        tfShowBookNumber = new javax.swing.JTextField();
        tfShowBookName = new javax.swing.JTextField();
        tfShowBookAuthor = new javax.swing.JTextField();
        tfShowBookIBNS = new javax.swing.JTextField();
        tfShowBookPublisher = new javax.swing.JTextField();

        jLabel26.setForeground(new java.awt.Color(0, 102, 255));
        jLabel26.setText("Mã sách:");

        jLabel28.setForeground(new java.awt.Color(0, 102, 255));
        jLabel28.setText("Tên sách:");

        jLabel30.setForeground(new java.awt.Color(0, 102, 255));
        jLabel30.setText("Tác giả:");

        jLabel32.setForeground(new java.awt.Color(0, 102, 255));
        jLabel32.setText("NXB:");

        jLabel34.setForeground(new java.awt.Color(0, 102, 255));
        jLabel34.setText("IBNS:");

        tbShowBookCopyInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbShowBookCopyInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbShowBookCopyInfoMouseReleased(evt);
            }
        });
        jscrollpane.setViewportView(tbShowBookCopyInfo);

        tfShowBookNumber.setEditable(false);

        tfShowBookName.setEditable(false);

        tfShowBookAuthor.setEditable(false);

        tfShowBookIBNS.setEditable(false);

        tfShowBookPublisher.setEditable(false);

        javax.swing.GroupLayout panelShowBookInfoLayout = new javax.swing.GroupLayout(panelShowBookInfo);
        panelShowBookInfo.setLayout(panelShowBookInfoLayout);
        panelShowBookInfoLayout.setHorizontalGroup(
            panelShowBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShowBookInfoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelShowBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelShowBookInfoLayout.createSequentialGroup()
                        .addGroup(panelShowBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel32)
                            .addComponent(jLabel34))
                        .addGap(9, 9, 9))
                    .addGroup(panelShowBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel26)
                        .addComponent(jLabel28)))
                .addGap(52, 52, 52)
                .addGroup(panelShowBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfShowBookIBNS, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfShowBookName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfShowBookNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfShowBookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfShowBookPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jscrollpane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );
        panelShowBookInfoLayout.setVerticalGroup(
            panelShowBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShowBookInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelShowBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(tfShowBookNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelShowBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(tfShowBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelShowBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(tfShowBookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelShowBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(tfShowBookPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelShowBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(tfShowBookIBNS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jscrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelShowBookInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(panelShowBookInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbShowBookCopyInfoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbShowBookCopyInfoMouseReleased

    }//GEN-LAST:event_tbShowBookCopyInfoMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JScrollPane jscrollpane;
    private javax.swing.JPanel panelShowBookInfo;
    private javax.swing.JTable tbShowBookCopyInfo;
    private javax.swing.JTextField tfShowBookAuthor;
    private javax.swing.JTextField tfShowBookIBNS;
    private javax.swing.JTextField tfShowBookName;
    private javax.swing.JTextField tfShowBookNumber;
    private javax.swing.JTextField tfShowBookPublisher;
    // End of variables declaration//GEN-END:variables
    
    public void setDataShowBookInfo(String bookNumber, String name, String author, String publisher,String ibns, BookCopyTableModel bookCopyTableModel){
        tfShowBookNumber.setText(bookNumber);
        tfShowBookName.setText(name);
        tfShowBookAuthor.setText(author);
        tfShowBookPublisher.setText(publisher);
        tbShowBookCopyInfo.setModel(bookCopyTableModel);
        tfShowBookIBNS.setText(ibns);
    }
}
