package main.view;

import book.view.BookCopyTableModel;
import book.view.BookTableModel;
import book.view.MyComboboxModel;
import book.view.PanelShowBookInfo;
import java.awt.event.ActionListener;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.JOptionPane;

public class MainForm extends javax.swing.JFrame implements IMainForm {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setTextForComponent();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        tbShowBook = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnLogIn = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        tfSearchBook = new javax.swing.JTextField();
        cbBookListCategory = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbShowBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scrollPane.setViewportView(tbShowBook);

        btnLogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/login_icon.png"))); // NOI18N
        btnLogIn.setText("Đăng nhập");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_search.png"))); // NOI18N
        btnSearch.setText("Tìm kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/register_icon.png"))); // NOI18N
        btnRegister.setText("Đăng ký");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfSearchBook, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbBookListCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegister)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbBookListCategory)
                    .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLogIn)
                            .addComponent(btnRegister)))
                    .addComponent(tfSearchBook, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrollPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogInActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cbBookListCategory;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tbShowBook;
    private javax.swing.JTextField tfSearchBook;
    // End of variables declaration//GEN-END:variables

    private void setTextForComponent() {
        setResizable(false);
        setTitle(MainFormConstants.TITLE_FORM);
        tbShowBook.setFillsViewportHeight(true);
    }

    @Override
    public void closeForm() {
        super.dispose();
    }

    @Override
    public void setVisibleForm(boolean isVisible) {
        setVisible(isVisible);
    }

    @Override
    public void setLogInButtonActionListener(ActionListener listener) {
        btnLogIn.addActionListener(listener);
    }

    @Override
    public void setButtonExitActionListener(WindowListener listener) {
        this.addWindowListener(listener);
    }

    @Override
    public MainForm getMainFormInstance() {
        return this;
    }

    @Override
    public void setButtonRegisterActionListener(ActionListener listener) {
        btnRegister.addActionListener(listener);
    }

    @Override
    public void displayNewBook(BookTableModel bookTableModel) {
        tbShowBook.setModel(bookTableModel);
    }

    @Override
    public void showListCategoryBook(MyComboboxModel myComboboxModel) {
        cbBookListCategory.setModel(myComboboxModel);
        cbBookListCategory.setSelectedIndex(0);
    }

    @Override
    public void setComboBoxCategoryBookActionListener(ActionListener listener) {
        cbBookListCategory.addActionListener(listener);
    }

    @Override
    public int getComboBoxCategoryBookSelectedIndex() {
        return cbBookListCategory.getSelectedIndex();
    }

    @Override
    public void setTaleShowBookMouseListener(MouseListener listener) {
        tbShowBook.addMouseListener(listener);
    }

    @Override
    public int getTableListBookResultRowSelected(MouseEvent e) {
        return tbShowBook.rowAtPoint(e.getPoint());
    }

    @Override
    public void setDataBookToShow(String bookNumber, String name, String author, String publisher, String ibns, BookCopyTableModel bookCopyTableModel) {
        PanelShowBookInfo panel=new PanelShowBookInfo();
        panel.setDataShowBookInfo(bookNumber, name, author, publisher, ibns, bookCopyTableModel);
        JOptionPane.showConfirmDialog(null, panel, bookNumber+"-"+name,JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE);
    }

    @Override
    public void setButtonSearchBookActionListener(ActionListener listener) {
        btnSearch.addActionListener(listener);
    }

    @Override
    public String getTextFieldSearchBook() {
        return tfSearchBook.getText();
    }

    @Override
    public void setTextFieldSearchBookKeyListener(KeyListener listener) {
        tfSearchBook.addKeyListener(listener);
    }

    @Override
    public void doButtonSearchBookClick() {
        btnSearch.doClick();
    }
    
}
